pipeline {
    agent any

    environment {
        SERVER_IP = credentials('ubuntu_24LTS_ip')
    }
    stages {
        stage('Setup') {
            steps {
                sh '''
                    pip3 install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                sh "pytest"

            }
        }

        stage('Package code') {
            steps {
                sh "zip -r myapp.zip ./* -x '*.git*'"
                sh "ls -lart"
            }
        }

        stage('Deploy to Ubuntu 24 LTS') {
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'ssh-key', keyFileVariable: 'ubuntu_private_sshkey', usernameVariable: 'username')]) {
                    sh '''
                    scp -i $ubuntu_private_sshkey -o StrictHostKeyChecking=no myapp.zip  ${username}@${SERVER_IP}:/home/rohith/
                    ssh -i $ubuntu_private_sshkey -o StrictHostKeyChecking=no ${username}@${SERVER_IP} << EOF
                        unzip -o /home/rohith/myapp.zip -d /home/rohith/app/
                        source app/venv/bin/activate
                        cd /home/rohith/app/
                        pip install -r requirements.txt
                        sudo systemctl restart flaskapp.service
EOF
                    '''
                }
            }
        }
       
        
       
        
    }
}