pipeline {
    agent any

    environment {
        SERVER_IP = credentials('ubuntu_24LTS_ip')
    }
    stages {
        stage('Setup') {
            steps {
                sh '''
                    cd 02-single-server-deployment

                    python3 -m venv venv
                    venv/bin/python -m pip install --upgrade pip
                    venv/bin/python -m pip install -r requirements.txt
                '''
            }
        }

        stage('Testing') {
            steps {
                sh '''
                    cd 02-single-server-deployment

                    venv/bin/python -m pytest
                '''
            }
        }  

        stage('Package code') {
            steps {
                sh '''
                    cd 02-single-server-deployment

                    zip -r myapp.zip . \
                        -x "venv/*" \
                        -x ".git/*" \
                        -x "__pycache__/*" \
                        -x ".pytest_cache/*"

                    ls -lh myapp.zip
                '''
            }
        }
        stage('Deploy - Remote Install & Restart') {
            steps {
                withCredentials([sshUserPrivateKey(
                    credentialsId: 'ubuntu_private_sshkey',
                    keyFileVariable: 'MY_SSH_KEY',
                    usernameVariable: 'username'
                )]) {
                    sh '''
                        cd 02-single-server-deployment

                        echo "==> Copying artifact"
                        scp -i $MY_SSH_KEY -o StrictHostKeyChecking=no \
                            myapp.zip ${username}@${SERVER_IP}:/home/rohith/

                        echo "==> Running remote deploy"
                        ssh -i $MY_SSH_KEY -o StrictHostKeyChecking=no \
                            ${username}@${SERVER_IP} "
                                set -e &&
                                cd /home/rohith &&
                                unzip -o myapp.zip -d app &&
                                cd app &&
                                /home/rohith/app/venv/bin/pip install -r requirements.txt &&
                                sudo systemctl restart flaskapp.service &&
                                echo DEPLOYMENT_SUCCESS
                            "
                        '''
                    }
            }
        }    
           
    }
}