pipeline {
    agent any

    environment {
        SERVER_IP = credentials('ubuntu_24LTS_ip')
    }
    stages {
        stage('Setup') {
            steps {
                sh '''
                    cd 02-single-server-deployment

                    python3 -m venv venv
                    venv/bin/python -m pip install --upgrade pip
                    venv/bin/python -m pip install -r requirements.txt
                '''
            }
        }

        stage('Testing') {
            steps {
                sh '''
                    cd 02-single-server-deployment

                    venv/bin/python -m pytest
                '''
            }
        }        
           
    }
}